// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oewmybuybbqrwdebljzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ld215YnV5YmJxcndkZWJsanp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5Nzk3NzIsImV4cCI6MjA2NzU1NTc3Mn0.Yxh637MZH994i8RY77nBdAuha-Uccz-pr8OCX7pMjz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});